concurrent = 5
check_interval = 0
connection_max_age = "15m0s"
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "Gitlabrunner-docker"
  url = "https://gitlab-italent.com/"
  id = 30
  token = ""
  token_obtained_at = 2025-01-07T07:55:01Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  [runners.custom_build_dir]
  [runners.cache]
    MaxUploadedArchiveSize = 0
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "ubuntu-devops"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0
    network_mtu = 0
root@smartconx-gitlab-runner:/home/user#
root@smartconx-gitlab-runner:/home/user# cat /etc/gitlab-runner/config.toml
concurrent = 15
check_interval = 0
connection_max_age = "15m0s"
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "gitlab-runner for"
  url = "https://gitlab.com/"
  id = 32
  token = ""
  token_obtained_at = 2025-02-19T06:53:16Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  [runners.custom_build_dir]
  [runners.cache]
    Type = "azure"
    Path = "gitlab-ci-cache"
    Shared = true
    MaxUploadedArchiveSize = 0
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
    AccountName = "conxgitalbcache"
    AccountKey = ""
    ContainerName = "gitlab"
  [runners.docker]
    tls_verify = false
    image = "/gitlab-dockerimage:latest-28-01-2025"
    privileged = true
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/var/lib/docker","/cache"]
    shm_size = 0
    network_mtu = 0
    pull_policy = "if-not-present"
